#!/usr/bin/env sh
#Should not be needed anymore uio_pruss is loaded at boot
#along with the board
/sbin/modprobe uio_pruss
cp ./dts/ROBOT-00A0.dtbo $FW
echo ROBOT > $SLOTS
#cp ./dts/BB-PRUPID-MOTOR-00A0.dtbo $FW
#echo BB-PRUPID-MOTOR > $SLOTS
./main
